import { createContext, useContext, useState, useEffect } from 'react'

const translations = {
  es: {
    'nav.about': 'Sobre mí',
    'nav.skills': 'Skills',
    'nav.projects': 'Proyectos',
    'nav.contact': 'Contacto',
    'nav.cv': '↓ CV PDF',
    'hero.badge': 'DISPONIBLE PARA PROYECTOS · COSTA RICA',
    'hero.name.last': 'Jiménez',
    'hero.subtitle': 'Desarrollador de Software & Analista de Datos',
    'hero.desc': 'Convierto ideas complejas en aplicaciones elegantes y datos en decisiones. Full-stack, sistemas de gestión y análisis con propósito.',
    'hero.btn.primary': 'Ver proyectos',
    'hero.btn.secondary': 'Hablemos →',
    'stats.projects': 'PROYECTOS',
    'stats.experience': 'AÑOS DE EXPERIENCIA',
    'stats.tech': 'TECNOLOGÍAS',
    'stats.dedication': 'DEDICACIÓN',
    'about.tag': 'SOBRE MÍ',
    'about.heading': 'Ingeniería precisa, hecha con criterio propio.',
    'about.p1': 'Soy ingeniero en sistemas y desarrollador full-stack. Diseño y construyo sistemas de gestión empresarial —planillas, facturación, contabilidad, control operativo— y los conecto con análisis de datos que convierten números en decisiones.',
    'about.p2': 'Mi enfoque combina rigor técnico y claridad: producto funcional, mantenible y bien pensado. Busco siempre la herramienta correcta, no la de moda.',
    'about.tag1': 'Full-stack',
    'about.tag2': 'Análisis de datos',
    'about.tag3': 'APIs & integración',
    'about.tag4': 'Business Intelligence',
    'skills.tag': 'HABILIDADES',
    'skills.heading': 'El stack con el que construyo',
    'skills.dev': 'DESARROLLO',
    'skills.data': 'DATOS & BI',
    'skills.advanced': 'Avanzado',
    'skills.intermediate': 'Intermedio',
    'projects.tag': 'PROYECTOS',
    'projects.heading': 'Sistemas que están en producción',
    'projects.1.title': 'Sistema de Planillas y RRHH',
    'projects.1.desc': 'Aplicación multiplataforma para gestión de empleados, cálculo de salarios, planillas y recursos humanos.',
    'projects.2.title': 'Facturación Electrónica',
    'projects.2.desc': 'Sistema completo de facturación electrónica que cumple los requisitos legales de Costa Rica.',
    'projects.3.title': 'Contabilidad Web',
    'projects.3.desc': 'Aplicación contable con gestión de asientos, reportes financieros y control de activos.',
    'projects.4.title': 'Financiamiento Automotriz',
    'projects.4.desc': 'Plataforma de financiamientos con cálculo de cuotas, tasas de interés y seguimiento de pagos.',
    'projects.5.title': 'Control de Visitas',
    'projects.5.desc': 'App multiempresa para gestión de entradas y salidas, roles, control de horas y monitoreo en tiempo real.',
    'projects.6.title': 'Experiencia Web 3D',
    'projects.6.desc': 'Sitio interactivo con Three.js: escenas 3D, animaciones y una presentación visual de alto impacto.',
    'contact.tag': 'CONTACTO',
    'contact.heading': '¿Construimos algo juntos?',
    'contact.location.label': 'UBICACIÓN',
    'contact.location': 'San Ramón, Alajuela · Costa Rica',
    'contact.phone.label': 'TELÉFONO',
  },
  en: {
    'nav.about': 'About',
    'nav.skills': 'Skills',
    'nav.projects': 'Projects',
    'nav.contact': 'Contact',
    'nav.cv': '↓ Resume PDF',
    'hero.badge': 'AVAILABLE FOR PROJECTS · COSTA RICA',
    'hero.name.last': 'Jiménez',
    'hero.subtitle': 'Software Developer & Data Analyst',
    'hero.desc': 'I turn complex ideas into elegant applications and data into decisions. Full-stack, management systems and analytics with purpose.',
    'hero.btn.primary': 'View projects',
    'hero.btn.secondary': "Let's talk →",
    'stats.projects': 'PROJECTS',
    'stats.experience': 'YEARS OF EXPERIENCE',
    'stats.tech': 'TECHNOLOGIES',
    'stats.dedication': 'DEDICATION',
    'about.tag': 'ABOUT ME',
    'about.heading': 'Precise engineering, built with my own judgment.',
    'about.p1': "I'm a systems engineer and full-stack developer. I design and build enterprise management systems —payroll, billing, accounting, operations control— and pair them with data analytics that turn numbers into decisions.",
    'about.p2': 'My approach blends technical rigor with clarity: functional, maintainable, well-considered product. I look for the right tool, not the trendy one.',
    'about.tag1': 'Full-stack',
    'about.tag2': 'Data analysis',
    'about.tag3': 'APIs & integration',
    'about.tag4': 'Business Intelligence',
    'skills.tag': 'SKILLS',
    'skills.heading': 'The stack I build with',
    'skills.dev': 'DEVELOPMENT',
    'skills.data': 'DATA & BI',
    'skills.advanced': 'Advanced',
    'skills.intermediate': 'Intermediate',
    'projects.tag': 'PROJECTS',
    'projects.heading': 'Systems running in production',
    'projects.1.title': 'Payroll & HR System',
    'projects.1.desc': 'Cross-platform app for employee management, salary calculation, payroll and human resources.',
    'projects.2.title': 'Electronic Invoicing',
    'projects.2.desc': 'Complete e-invoicing system compliant with Costa Rica legal requirements.',
    'projects.3.title': 'Web Accounting',
    'projects.3.desc': 'Accounting app with journal entries, financial reports and asset control.',
    'projects.4.title': 'Auto Financing',
    'projects.4.desc': 'Financing platform with installment calculation, interest rates and payment tracking.',
    'projects.5.title': 'Visitor Control',
    'projects.5.desc': 'Multi-company app for entry/exit management, roles, time control and real-time monitoring.',
    'projects.6.title': '3D Web Experience',
    'projects.6.desc': 'Interactive Three.js site: 3D scenes, animations and a high-impact visual presentation.',
    'contact.tag': 'CONTACT',
    'contact.heading': 'Shall we build something?',
    'contact.location.label': 'LOCATION',
    'contact.location': 'San Ramón, Alajuela · Costa Rica',
    'contact.phone.label': 'PHONE',
  },
}

const LangContext = createContext(null)

export function LangProvider({ children }) {
  const [lang, setLang] = useState('es')
  const toggleLang = () => setLang(l => l === 'es' ? 'en' : 'es')
  const t = (key) => translations[lang][key] ?? key
  useEffect(() => { document.documentElement.lang = lang }, [lang])
  return <LangContext.Provider value={{ lang, toggleLang, t }}>{children}</LangContext.Provider>
}

export function useLang() {
  return useContext(LangContext)
}
